name = "gasdex-ratings"
main = "worker.js"
compatibility_date = "2024-06-01"
workers_dev = true

# KV namespace binding for storing ballots and aggregates
[[kv_namespaces]]
binding = "GASDEX_RATINGS"
id = "3c1d4303beee49d684a8b40e1261f906"
preview_id = "2975a305f62449b5b07198c3036dbffe"

# Environment-specific settings
[env.production]
routes = [
  { pattern = "ratings.gasdex.co.uk/*", zone_name = "gasdex.co.uk" }
]

[env.staging]
routes = [
  { pattern = "ratings-staging.gasdex.co.uk/*", zone_name = "gasdex.co.uk" }
]
